
services:
  pokeapidb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pokeapidb
    environment:
      SA_PASSWORD: "Sw12345678"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend

  pokeapiapp:
    build:
      context: .
      dockerfile: ./PokemonApi.Api/Dockerfile
    container_name: pokeapiapp
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__Database=Server=pokeapidb;Database=PokeApiDb;User Id=sa;Password=Sw12345678;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - pokeapidb
    networks:
      - backend

networks:
  backend:
    driver: bridge